global:
  slack_api_url: "https://hooks.slack.com/services/"

templates:
  - template/*

route:
  receiver: slack
  group_by: [ 'instance', 'alertname', 'job', 'containername' ]
  group_wait: 0s
  group_interval: 1s
  repeat_interval: 30m


receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
        username: '{{ template "slack.username" . }}'
        channel: '{{ template "slack.channel" . }}'
        icon_emoji: '{{ template "slack.icon_emoji" . }}'
        title_link: '{{ template "slack.title_link" . }}'
        title: '{{ template "slack.title" . }}'
        color: '{{ template "slack.color" . }}'
        text: '{{ template "slack.text" . }}'