global:
  scrape_interval: 10s
  scrape_timeout: 5s
  
#  evaluation_interval: 5s
#  query_log_file: /prometheus/query.log

#rule_files:
#  - rule_files/alerting/*.yml
#  - rule_files/recording/*.yml

scrape_configs:
# prometheus
  - job_name: prometheus
    file_sd_configs:
      - files:
        - sd_configs/file/prometheus.yml
        refresh_interval: 5m
    relabel_configs:
        # add port label
      - action:         replace
        source_labels:  [__address__]
        target_label:   port
        regex:          ^(.*):(\d{1,5})$
        replacement:    ${2}
        # delete port label from instance label
      - action:         replace
        source_labels:  [__address__]
        target_label:   instance
        regex:          ^(.*)(:\d{1,5})$
        replacement:    ${1}
      
# cadvisor
  - job_name: cadvisor
    file_sd_configs:
      - files:
        - sd_configs/file/cadvisor.yml
        refresh_interval: 5m
    relabel_configs:
        # add port label
      - action:         replace
        source_labels:  [__address__]
        target_label:   port
        regex:          ^(.*):(\d{1,5})$
        replacement:    ${2}
        # delete port from instance label
      - action:         replace
        source_labels:  [__address__]
        target_label:   instance
        regex:          ^(.*)(:\d{1,5})$
        replacement:    ${1}
    metric_relabel_configs:
        # replace root cgroup's 'id' label with 'name' label
      - action:         replace
        source_labels:  [id]
        target_label:   name
        regex:          ^/$
        replacement:    ${0}
        # drop all 'id', 'image' label
      - action:         labeldrop
        regex:          (^id$|^image$)
        
# node_exporter
  - job_name: node_exporter
    file_sd_configs:
      - files:
        - sd_configs/file/node_exporter.yml
        refresh_interval: 5m
    relabel_configs:
        # add port label
      - action:         replace
        source_labels:  [__address__]
        target_label:   port
        regex:          ^(.*):(\d{1,5})$
        replacement:    ${2}
        # delete port from instance label
      - action:         replace
        source_labels:  [__address__]
        target_label:   instance
        regex:          ^(.*)(:\d{1,5})$
        replacement:    ${1}
#   params:
#      collect[]: ['cpu']
        
# spring_actuator
  - job_name: spring_actuator
    metrics_path: /actuator/prometheus
    scheme: https
    tls_config:
      insecure_skip_verify: true
    file_sd_configs:
      - files:
        - sd_configs/file/spring_actuator.yml
        refresh_interval: 5m
    relabel_configs:
        # add port label
      - action:         replace
        source_labels:  [__address__]
        target_label:   port
        regex:          ^(.*):(\d{1,5})$
        replacement:    ${2}
        # delete port from instance label
      - action:         replace
        source_labels:  [__address__]
        target_label:   instance
        regex:          ^(.*)(:\d{1,5})$
        replacement:    ${1}
        
# harbor
#  - job_name: harbor_exporter
#    static_configs:
#      - targets: ['localhost:9091']
#  - job_name: harbor_core
#    static_configs:
#      - targets: ['localhost:9091']
#    params:
#      comp: ['core']
#  - job_name: harbor_registry
#    static_configs:
#      - targets: ['localhost:9091']
#    params:
#      comp: ['registry']

# Alerting specifies settings related to the Alertmanager
#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets: ['192.168.136.61:9093']