{
 "title": "CPU",
 "tags": [
  "default",
  "host",
  "cgroup",
  "spring"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(up, instance)" } },
   {
    "name": "cpu",
    "query": {
     "query": "label_values(node_cpu_seconds_total{instance=\"$instance\"}, cpu)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_cpu_load_average_10s{instance=\"$instance\"}, name)"
    }
   },
   {
    "name": "spring_application",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{instance=\"$instance\"}, application)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HOST", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Load Avg",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$instance\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=\"$instance\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=\"$instance\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Process Status",
   "type": "stat",
   "description": "blocked: Number of processes blocked waiting for I/O to complete\n\nrunning: Number of processes in runnable state",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_procs_blocked{instance=\"$instance\"}",
     "legendFormat": "blocked"
    },
    {
     "expr": "node_procs_running{instance=\"$instance\"}",
     "legendFormat": "running"
    }
   ]
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 } },
  {
   "title": "Usage by mode (stack)",
   "type": "timeseries",
   "description": "user: Time spent in user mode\n\nnide: Time spent in user mode with low priority (cide)\n\nsystem: Time spent in system mode\n\nidle: Time spend in the idle task\n\niowait: Time waiting for I/O to complete. This value is not reliable\n\nirq: Time servicing interrupts\n\nsoftirq: Time servicing softirqs\n\nsteal: Stolen time, which is the time spent in other operating systmes when running in a virtualized environment\n\nguest: Time spent running a virtual CPU for guest operating systems under the control of the Linux kernel\n\nguest_nice: Time spent running a niced guest (virtual CPU for guest operating systems under the control of the Linux kernel)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (mode) (rate(node_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval])) /\nscalar(sum(rate(node_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval])) + sum(rate(node_cpu_guest_seconds_total{instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode) (rate(node_cpu_guest_seconds_total{instance=\"$instance\"}[$__rate_interval])) /\nscalar(sum(rate(node_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval])) + sum(rate(node_cpu_guest_seconds_total{instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{mode}}(guest)"
    }
   ]
  },
  {
   "title": "HOST (CPU - $cpu)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "cpu",
   "collapsed": true,
   "panels": [
    {
     "title": "Usage by mode (stack)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (mode) (rate(node_cpu_seconds_total{instance=\"$instance\", cpu=\"$cpu\"}[$__rate_interval])) /\nscalar(sum(rate(node_cpu_seconds_total{instance=\"$instance\", cpu=\"$cpu\"}[$__rate_interval])) + sum(rate(node_cpu_guest_seconds_total{instance=\"$instance\", cpu=\"$cpu\"}[$__rate_interval])))",
       "legendFormat": "{{mode}}"
      },
      {
       "expr": "sum by (mode) (rate(node_cpu_guest_seconds_total{instance=\"$instance\", cpu=\"$cpu\"}[$__rate_interval])) /\nscalar(sum(rate(node_cpu_seconds_total{instance=\"$instance\", cpu=\"$cpu\"}[$__rate_interval])) + sum(rate(node_cpu_guest_seconds_total{instance=\"$instance\", cpu=\"$cpu\"}[$__rate_interval])))",
       "legendFormat": "{{mode}}(guest)"
      }
     ]
    }
   ]
  },
  {
   "title": "CGROUPS ($container)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "container",
   "collapsed": true,
   "panels": [
    {
     "title": "Load Avg(10s)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "container_cpu_load_average_10s{instance=\"$instance\", name=\"${container:raw}\"} / 1000"
      }
     ]
    },
    {
     "title": "Num of Task",
     "type": "stat",
     "gridPos": { "h": 4, "w": 10, "x": 3, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "container_tasks_state{instance=\"$instance\", name=\"${container:raw}\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Usage",
     "type": "timeseries",
     "description": "used: Cumulative cpu time consumed by container. Used ≠ user + system. For more information about this, refer to cgroups",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg (rate(container_cpu_usage_seconds_total{instance=\"$instance\", name=\"${container:raw}\"}[$__rate_interval]))",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Usage (stack)",
     "type": "timeseries",
     "description": "system: Cumulative system cpu time consumed by container\n\nuser: Cumulative user cpu time consumed by container",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(container_cpu_system_seconds_total{instance=\"$instance\", name=\"${container:raw}\"}[$__rate_interval])",
       "legendFormat": "user"
      },
      {
       "expr": "rate(container_cpu_user_seconds_total{instance=\"$instance\", name=\"${container:raw}\"}[$__rate_interval])",
       "legendFormat": "system"
      }
     ]
    }
   ]
  },
  {
   "title": "Spring Application ($spring_application)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "spring_application",
   "collapsed": true,
   "panels": [
    {
     "title": "Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "process_cpu_usage{instance=\"$instance\", application=\"${spring_application:raw}\"}",
       "legendFormat": "{{application}}"
      }
     ]
    }
   ]
  }
 ]
}