{
 "title": "Memory",
 "tags": [
  "default",
  "host",
  "cgroup",
  "spring"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"(node_exporter||cadvisor)\"}, instance)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_cpu_load_average_10s{instance=\"$instance\"}, name)"
    }
   },
   {
    "name": "spring_application",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{instance=\"$instance\"}, application)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HOST", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mem Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Swap Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Mem Available",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"$instance\"} / node_memory_MemTotal_bytes{instance=\"$instance\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Mem Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemFree_bytes{instance=\"$instance\"}) / node_memory_MemTotal_bytes{instance=\"$instance\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Swap Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1 - (node_memory_SwapFree_bytes{instance=\"$instance\"} / node_memory_SwapTotal_bytes{instance=\"$instance\"})",
     "legendFormat": "Used"
    }
   ]
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 } },
  {
   "title": "Usage",
   "type": "timeseries",
   "description": "total: Total usable RAM (i.e., physical RAM minus a few reserved bits and the kernel binary code)\n\nused: Used memory. Total - Free\n\nanonymous: Active_anon + Inactive_anon. The amount of anonymous and tmpfs/shmem memory",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemFree_bytes{instance=\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_Active_anon_bytes{instance=\"$instance\"} + node_memory_Inactive_anon_bytes{instance=\"$instance\"}",
     "legendFormat": "aAnonymous"
    }
   ]
  },
  {
   "title": "Free and Available",
   "type": "timeseries",
   "description": "free: Unused(empty) memory\n\navailable: Estimation of how much memory is available for starting new applications, without swapping",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"$instance\"}",
     "legendFormat": "available"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$instance\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Shmem",
   "type": "timeseries",
   "description": "shmem: Amount of memory (mostly) consumed in tmpfs filesystems",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Shmem_bytes{instance=\"$instance\"}",
     "legendFormat": "shmem"
    }
   ]
  },
  {
   "title": "Slab (stack)",
   "type": "timeseries",
   "description": "slab: In-kernel data structures cache. SReclaimable + sUnreclaim\n\nsReclaimable: Part of Slab, that might be reclaimed, such as caches\n\nsUnreclaim: Part of Slab, that cannot be reclaimed on memory pressure",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Slab_bytes{instance=\"$instance\"}",
     "legendFormat": "slab (Total)"
    },
    {
     "expr": "node_memory_SReclaimable_bytes{instance=\"$instance\"}",
     "legendFormat": "sRelclaimable"
    },
    {
     "expr": "node_memory_SUnreclaim_bytes{instance=\"$instance\"}",
     "legendFormat": "sUnreclaim"
    }
   ]
  },
  {
   "title": "Buffers and Cached (stack)",
   "type": "timeseries",
   "description": "buffers: Buffer cache. Relatively temporary storage for raw disk blocks that shouldn't get tremendously large (20 MB or so)\n\ncached: In-memory cache for files read from the disk (the page cache).  Doesn't include SwapCached",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$instance\"}",
     "legendFormat": "buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$instance\"}",
     "legendFormat": "cached"
    }
   ]
  },
  {
   "title": "Swap (stack)",
   "type": "timeseries",
   "description": "total:  Total amount of swap space available\n\nused: Used swap. Total - Free\n\nfree: Unused swap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$instance\"} - node_memory_SwapFree_bytes{instance=\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_SwapFree_bytes{instance=\"$instance\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "CGROUPS ($container)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "container",
   "collapsed": true,
   "panels": [
    {
     "title": "Limit",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "container_spec_memory_limit_bytes{instance=\"$instance\", name=\"${container:raw}\"}",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Swap Limit",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "container_spec_memory_swap_limit_bytes{instance=\"$instance\", name=\"${container:raw}\"} - container_spec_memory_limit_bytes{instance=\"$instance\", name=\"${container:raw}\"}",
       "legendFormat": "Swap Limit"
      }
     ]
    },
    {
     "title": "Mem Used",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{instance=\"$instance\", name=\"${container:raw}\"} / (container_spec_memory_limit_bytes{instance=\"$instance\", name=\"${container:raw}\"} > 0)",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Swap Used",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(container_memory_swap{instance=\"$instance\", name=\"$container\"} / ((container_spec_memory_swap_limit_bytes{instance=\"$instance\", name=\"$container\"} > 0) - container_spec_memory_limit_bytes{instance=\"$instance\", name=\"$container\"}))",
       "legendFormat": "Used"
      }
     ]
    },
    { "type": "mxswat-separator-panel", "gridPos": { "h": 4, "w": 13, "x": 8, "y": 20 } },
    {
     "title": "Usage",
     "type": "timeseries",
     "description": "rss: mapped anon pages. The amount of memory that doesn't correspond to anything on disk. anonymous + swap cache(includes transparent hugepages). This should not be confused with the RSS(Resident Set Size, rss + mapped_file)\n\nusage: total current memory usage by processes in the cgroup. It's a fuzz value for efficient access. If you want to know more exact memory usage, you should use rss + cache\n\nworking set: The amount of working set memory and it includes recently accessed memory, dirty memory. usage - inactive_file",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{instance=\"$instance\", name=\"${container:raw}\"}",
       "legendFormat": "usage"
      },
      {
       "expr": "container_memory_working_set_bytes{instance=\"$instance\",name=\"${container:raw}\"}",
       "legendFormat": "working set"
      },
      {
       "expr": "container_memory_rss{instance=\"$instance\", name=\"${container:raw}\"}",
       "legendFormat": "rss"
      }
     ]
    },
    {
     "title": "Cache",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_cache{instance=\"$instance\", name=\"${container:raw}\"}",
       "legendFormat": "cache"
      }
     ]
    },
    {
     "title": "Swap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_swap{instance=\"$instance\", name=\"${container:raw}\"}",
       "legendFormat": "used"
      }
     ]
    }
   ]
  },
  {
   "title": "Spring Application ($spring_application)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "repeat": "spring_application",
   "collapsed": true,
   "panels": [
    {
     "title": "Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (application) (jvm_memory_used_bytes{instance=\"$instance\", application=\"${spring_application:raw}\"})",
       "legendFormat": "{{application}}"
      }
     ]
    }
   ]
  }
 ]
}