{
 "title": "Spring",
 "tags": [
  "default",
  "spring"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(up, instance)" } },
   {
    "name": "application",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{instance=\"$instance\"}, application)"
    }
   },
   {
    "name": "uri",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\"}, uri)"
    }
   },
   {
    "name": "hikari_cp",
    "query": {
     "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "Start time of the JVM",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"$instance\", application=\"$application\"} * 1000",
     "legendFormat": "Start time"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Uptime of the JVM",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Number of processors available to the JVM",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "system_cpu_count{instance=\"$instance\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "File Descriptor Limit",
   "type": "stat",
   "description": "Usable maximum file descriptor count",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_files_max_files{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Hikari connection pool Overview",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(hikaricp_connections_usage_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "usage rate"
    },
    {
     "expr": "sum(rate(hikaricp_connections_usage_seconds_sum{instance=\"$instance\", application=\"$application\"}[$__rate_interval])) / sum(rate(hikaricp_connections_usage_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "usage duration"
    },
    {
     "expr": "sum(rate(hikaricp_connections_acquire_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "acquire rate"
    },
    {
     "expr": "sum(rate(hikaricp_connections_acquire_seconds_sum{instance=\"$instance\", application=\"$application\"}[$__rate_interval])) / sum(rate(hikaricp_connections_acquire_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "acquire duration"
    }
   ]
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 } },
  {
   "title": "Loaded Classes",
   "type": "stat",
   "description": "Number of classes that are currently loaded in the JVM",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{instance=\"$instance\", application=\"$application\"}"
    }
   ]
  },
  {
   "title": "File Descriptor Used",
   "type": "stat",
   "description": "Opend file descriptor count",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_files_open_files{instance=\"$instance\", application=\"$application\"}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "description": "Total memory used by the JVM",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "description": "The \"recent cpu usage\" for the JVM process",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "HTTP Overview",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "req rate"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "req duration"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", status=~\"2..\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "success rate"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Req rate",
   "type": "timeseries",
   "description": "HTTP request rate by endpoint",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Req duration",
   "type": "timeseries",
   "description": "HTTP request duration by endpoint",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\"}[$__rate_interval])) / sum by (uri) (rate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "sum (rate(http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\"}[$__rate_interval])) / sum (rate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Req Success rate",
   "type": "timeseries",
   "description": "HTTP request success rate by endpoint",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", status=~\"2..\"}[$__rate_interval])) / sum by (uri) (rate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", status=~\"2..\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "HTTP by endpoint ($uri)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "uri",
   "collapsed": true,
   "panels": [
    {
     "title": "Req rate",
     "type": "timeseries",
     "description": "HTTP request rate (Unit:  operations/sec)",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", uri=\"${uri:raw}\"}[$__rate_interval]))",
       "legendFormat": "rate"
      }
     ]
    },
    {
     "title": "Req rate",
     "type": "timeseries",
     "description": "HTTP request rate by HTTP status code (Unit:  operations/sec)",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (status) (rate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", uri=\"${uri:raw}\"}[$__rate_interval]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Req duration",
     "type": "timeseries",
     "description": "avg: Average request duration\n\nmax: Maximum request duration during a time window. The value resets to 0 when a new time window starts.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\", uri=\"${uri:raw}\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", uri=\"${uri:raw}\"}[$__rate_interval]))",
       "legendFormat": "avg"
      },
      {
       "expr": "max(http_server_requests_seconds_max{instance=\"$instance\", application=\"$application\", uri=\"${uri:raw}\"})",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  { "title": "Hikari", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Usage rate",
   "type": "timeseries",
   "description": "Connection usage rate by pool (Unit:  operations/sec)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(hikaricp_connections_usage_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval])",
     "legendFormat": "{{pool}}"
    },
    {
     "expr": "sum(rate(hikaricp_connections_usage_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Acquire rate",
   "type": "timeseries",
   "description": "Connection acquire rate by pool (Unit:  operations/sec)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(hikaricp_connections_acquire_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval])",
     "legendFormat": "{{pool}}"
    },
    {
     "expr": "sum(rate(hikaricp_connections_acquire_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Creation rate",
   "type": "timeseries",
   "description": "Connection creation rate by pool(Unit:  operations/sec)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(hikaricp_connections_creation_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval])",
     "legendFormat": "{{pool}}"
    },
    {
     "expr": "sum(rate(hikaricp_connections_creation_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Usage duration",
   "type": "timeseries",
   "description": "Connection usage duration by pool",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(hikaricp_connections_usage_seconds_sum{instance=\"$instance\", application=\"$application\"}[$__rate_interval]) / rate(hikaricp_connections_usage_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval])",
     "legendFormat": "{{pool}}"
    },
    {
     "expr": "sum(rate(hikaricp_connections_usage_seconds_sum{instance=\"$instance\", application=\"$application\"}[$__rate_interval])) / sum(rate(hikaricp_connections_usage_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Acquire duration",
   "type": "timeseries",
   "description": "Acquire usage duration by pool",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(hikaricp_connections_acquire_seconds_sum{instance=\"$instance\", application=\"$application\"}[$__rate_interval]) / rate(hikaricp_connections_acquire_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval])",
     "legendFormat": "{{pool}}"
    },
    {
     "expr": "sum(rate(hikaricp_connections_acquire_seconds_sum{instance=\"$instance\", application=\"$application\"}[$__rate_interval])) / sum(rate(hikaricp_connections_acquire_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Creation duration",
   "type": "timeseries",
   "description": "Acquire creation duration by pool",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(hikaricp_connections_creation_seconds_sum{instance=\"$instance\", application=\"$application\"}[$__rate_interval]) / rate(hikaricp_connections_creation_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval])",
     "legendFormat": "{{pool}}"
    },
    {
     "expr": "sum(rate(hikaricp_connections_creation_seconds_sum{instance=\"$instance\", application=\"$application\"}[$__rate_interval])) / sum(rate(hikaricp_connections_creation_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Hikari by pool ($hikari_cp)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "repeat": "hikari_cp",
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Connections",
     "type": "timeseries",
     "description": "connected: Total connections\n\npending: Pending threads\n\nactive: Active connections\n\nidle: Idle connections\n\nmax: Max connections\n\nmin: Min connections",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "hikaricp_connections{instance=\"$instance\", application=\"$application\", pool=\"${hikari_cp:raw}\"}",
       "legendFormat": "connected"
      },
      {
       "expr": "hikaricp_connections_pending{instance=\"$instance\", application=\"$application\", pool=\"${hikari_cp:raw}\"}",
       "legendFormat": "pending"
      },
      {
       "expr": "hikaricp_connections_active{instance=\"$instance\", application=\"$application\", pool=\"${hikari_cp:raw}\"}",
       "legendFormat": "active"
      },
      {
       "expr": "hikaricp_connections_idle{instance=\"$instance\", application=\"$application\", pool=\"${hikari_cp:raw}\"}",
       "legendFormat": "idle"
      },
      {
       "expr": "hikaricp_connections_max{instance=\"$instance\", application=\"$application\", pool=\"${hikari_cp:raw}\"}",
       "legendFormat": "max"
      },
      {
       "expr": "hikaricp_connections_min{instance=\"$instance\", application=\"$application\", pool=\"${hikari_cp:raw}\"}",
       "legendFormat": "min"
      }
     ]
    },
    {
     "title": "Timeout Connection rate",
     "type": "timeseries",
     "description": " Connection timeout rate",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_timeout_total{instance=\"$instance\", application=\"$application\", pool=\"${hikari_cp:raw}\"}[$__rate_interval])",
       "legendFormat": "rate"
      }
     ]
    },
    {
     "title": "Usage rate",
     "type": "timeseries",
     "description": "Connection usage rate (Unit:  operations/sec)",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_usage_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"${hikari_cp:raw}\"}[$__rate_interval])",
       "legendFormat": "rate"
      }
     ]
    },
    {
     "title": "Acquire rate",
     "type": "timeseries",
     "description": "Connection acquire rate (Unit:  operations/sec)",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_acquire_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"${hikari_cp:raw}\"}[$__rate_interval])",
       "legendFormat": "rate"
      }
     ]
    },
    {
     "title": "Creation rate",
     "type": "timeseries",
     "description": "Connection creation rate (Unit:  operations/sec)",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_creation_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"${hikari_cp:raw}\"}[$__rate_interval])",
       "legendFormat": "rate"
      }
     ]
    },
    {
     "title": "Usage duration",
     "type": "timeseries",
     "description": "Connection usage duration",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_usage_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"${hikari_cp:raw}\"}[$__rate_interval]) / rate(hikaricp_connections_usage_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"${hikari_cp:raw}\"}[$__rate_interval])",
       "legendFormat": "duration"
      },
      {
       "expr": "hikaricp_connections_usage_seconds_max{instance=\"$instance\", application=\"$application\", pool=\"${hikari_cp:raw}\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Acquire duration",
     "type": "timeseries",
     "description": "Acquire usage duration",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_acquire_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"${hikari_cp:raw}\"}[$__rate_interval]) / rate(hikaricp_connections_acquire_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"${hikari_cp:raw}\"}[$__rate_interval])",
       "legendFormat": "duration"
      },
      {
       "expr": "hikaricp_connections_acquire_seconds_max{instance=\"$instance\", application=\"$application\", pool=\"${hikari_cp:raw}\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Creation duration",
     "type": "timeseries",
     "description": "Acquire creation duration",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_creation_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"${hikari_cp:raw}\"}[$__rate_interval]) / rate(hikaricp_connections_creation_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"${hikari_cp:raw}\"}[$__rate_interval])",
       "legendFormat": "duration"
      },
      {
       "expr": "hikaricp_connections_creation_seconds_max{instance=\"$instance\", application=\"$application\", pool=\"${hikari_cp:raw}\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  { "title": "Tomcat (Session)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Active Session",
   "type": "timeseries",
   "description": "active: The number of current active HTTP session\n\nmax: The number of maximum active HTTP session",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "tomcat_sessions_active_current_sessions{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "active"
    },
    {
     "expr": "tomcat_sessions_active_max_sessions{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Session duration",
   "type": "timeseries",
   "description": "The duration of HTTP session by status (Unit:  counts/sec)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(tomcat_sessions_created_sessions_total{instance=\"$instance\", application=\"$application\"}[$__rate_interval])",
     "legendFormat": "created"
    },
    {
     "expr": "rate(tomcat_sessions_expired_sessions_total{instance=\"$instance\", application=\"$application\"}[$__rate_interval])",
     "legendFormat": "expired"
    },
    {
     "expr": "rate(tomcat_sessions_rejected_sessions_total{instance=\"$instance\", application=\"$application\"}[$__rate_interval])",
     "legendFormat": "rejected"
    }
   ]
  },
  { "title": "JVM CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "CPU Used",
   "type": "timeseries",
   "description": "{{application}}: The \"recent cpu usage\" for the JVM process\n\nhost: The \"recent cpu usage\" for the whole system",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "{{application}}"
    },
    {
     "expr": "system_cpu_usage{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "Number of Threads",
   "type": "timeseries",
   "description": "The current number of threads by status",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Number of Threads",
   "type": "timeseries",
   "description": "daemon: The current number of live daemon threads\n\nnon-daemon: The current number of live non-daemon threads\n\nmax: The peak live thread count since the JVM started or peak was reset",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_live_threads{instance=\"$instance\", application=\"$application\"} - jvm_threads_daemon_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "non-daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "description": "The total(heap + non-heap) amount of used memory",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", area=\"heap\"})",
     "legendFormat": "heap"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", area=\"nonheap\"})",
     "legendFormat": "non-heap"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "timeseries",
   "description": "The amount of used heap memory",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", area=\"heap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "non-Heap Used",
   "type": "timeseries",
   "description": "The amount of used non-heap memory",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", area=\"nonheap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "JVM GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "GC rate",
   "type": "timeseries",
   "description": "per-second average rate of GC operataions (Unit:  operations/sec)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause duration",
   "type": "timeseries",
   "description": "Time spent in GC pause",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{application=\"$application\", instance=\"$instance\"}[$__rate_interval])/rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{action}} ({{cause}}) max"
    }
   ]
  },
  {
   "title": "Allocated / Promoted rate",
   "type": "timeseries",
   "description": "allocated: Incremented for an increase in the size of the young generation memory pool after one GC to before the next\n\npromoted: Count of positive increases in the size of the old generation memory pool before GC to after GC",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\", application=\"$application\"}[$__rate_interval])",
     "legendFormat": "allocated"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\", application=\"$application\"}[$__rate_interval])",
     "legendFormat": "promoted"
    }
   ]
  },
  { "title": "Buffer Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  { "title": "Etc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Log rate",
   "type": "timeseries",
   "description": "per-second average rate of increase of log events (Unit:  counts/sec)",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(log4j2_events_total{instance=\"$instance\", application=\"$application\"}[$__rate_interval])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Opend Filed Descriptor",
   "type": "timeseries",
   "description": "The open file descriptor count",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_files_open_files{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "opend"
    }
   ]
  }
 ]
}