apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://192.168.136.61:9090
    uid: prometheus_datasource
    isDefault: true
    jsonData:
      timeInterval: 10s
      httpMethod: POST
    editable: false